### ISSUE TITLE
Would love a guide on the lua part on this :-)

### ISSUE THREAD

**Issue by Cmoen11** [2277/fivem-react-boilerplate#2]
Hi, I'm hyped that I just discovered this.. But I can't figure it quite out yet.. Could you give a quick example on how to do the lua part on this?

**Comment by 2277** [comment]
Sure! I work primary in C# but I'm sure I can pull something together.

**Comment by 2277** [comment]
All done. I'm not too familar with Lua, it uses Vespura's [JoinTransition](https://github.com/TomGrobbe/JoinTransition/blob/master) resource. I hope its sufficient.

Check the example directory of the master branch for a brief example. I include several features from my fivem-vue-boilerplate too.

A video of the example:
https://streamable.com/zqwdo
